name: Backend CI/CD

on:
  push:
    branches: [main, develop]

env:
  GH_VERSION: ${{ github.sha }}
  REGISTRY_NAME: ghcr.io
  REGISTRY_USER: janeonthegame
  IMAGE_NAME: janeonthegame-api

jobs:
  build-and-push:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true

      - name: Test
        run: npm run test || true

      - name: Build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags and labels)
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY_NAME }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.GH_VERSION }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64

      - name: Output Image name
        run: |
          echo "Image pushed to ${{ env.REGISTRY_NAME }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.GH_VERSION }}"

  update-manifest:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Checkout Helm Repo
        uses: actions/checkout@v4
        with:
          repository: janeonthegame/janeonthegame-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update tag in backend-values.yaml
        run: |
          echo "Updating to ${{ env.GH_VERSION }}"
          sed -i "s|tag:.*|tag: ${{ env.GH_VERSION }}|" environments/production/backend-values.yaml

      - name: Commit & push if changed
        run: |
          git add environments/production/backend-values.yaml
          if ! git diff --cached --quiet; then
            git commit -m "ci: bump backend image to ${{ env.GH_VERSION }} [skip ci]"
            git push origin main
          else
            echo "No changes to commit."
          fi
